version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: virtual-file-system-mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always

  redis:
    image: redis:7-alpine
    container_name: virtual-file-system-redis-2
    ports:
      - "61387:6379"
    volumes:
      - redis_data2:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mysql_db:
  redis_data2:
  data:
