version: '3.5'
services:
    mysql:
        image: mysql:8.0
        container_name: virtual-file-system-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 3307:3306
        volumes:
            - mysql_db:/var/lib/mysql
        restart: always

volumes:
    mysql_db:
    data:
