/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/api/cd": {
    /** Change current directory */
    get: {
      parameters: {
        query: {
          path: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @default Successfully change directory */
              message: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @default No directory found with the provided path! */
              message: string;
            };
          };
        };
      };
    };
  };
  "/api/cr": {
    /** Create new file or directory */
    post: {
      requestBody: {
        content: {
          "application/json": {
            path: string;
            data: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @default Successfully create file/directory */
              content: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
  };
  "/api/cat": {
    /** Retrieve content of the file */
    get: {
      parameters: {
        query: {
          path: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @default No file found with the provided path! */
              message: string;
            };
          };
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
