/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            usernameOrEmail: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @description User ID */
              id: string;
              email: string | null;
              username: string;
            };
          };
        };
      };
    };
  };
  "/auth/signup": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email?: string;
            username: string;
            password: string;
            firstName: string;
            lastName: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @description User ID */
              id: string;
              email: string | null;
              username: string;
            };
          };
        };
      };
    };
  };
  "/auth/logout": {
    delete: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
